name: Publish Android Bindings

on:
  workflow_dispatch:

jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Publish Bindings
        working-directory: ./android-bindings
        run: |
          make publish
