name: Hello World

on:
  workflow_dispatch:

jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Libs
        working-directory: ./android-bindings
        run: |
          make
